[project]
name = "command-k"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = []

[project.scripts]
command-k = "command_k:main"

[tool.uv]
package = true
